version: "3"
services:
  bot2:
    build: bot/
    container_name: bot2
    ports:
      - 4000:9000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: on-failure
    volumes:
      - ./bot_files:/bot_files
  admin2:
    build: admin/
    container_name: admin2
    ports:
      - 6000:8000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: on-failure
    volumes:
      - ./bot_files:/bot_files

networks:
  default:
    external: true
    name: bot_net2